on:
  push:
    branches:
      - main
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/setup-java@v3.11.0
        with:
          distribution: "temurin"
          java-version: "11"
      - uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: "3.10.2"
      - run: flutter pub get
      - run: flutter build apk --split-per-abi
      - run: |
          flutter build ios --release --no-codesign --no-tree-shake-icons
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*.apk,build/ios/iphoneos/app.ipa"
          tag: v1.0
