on:
  push:
    branches:
      - main
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "11"
          cache: "gradle"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - name: Install dependenices
        run: flutter pub get
      - name: Set up env variables
        env:
          MAPBOX_APIKEY: ${{ secrets.MAPBOX_APIKEY }}
          GOOGLE_MAPS_APIKEY: ${{ secrets.GOOGLE_MAPS_APIKEY }}
        run: |
          cat << EOF > .env
          MAPBOX_APIKEY=$MAPBOX_APIKEY
          GOOGLE_MAPS_APIKEY=$GOOGLE_MAPS_APIKEY
          EOF
      - run: dart run build_runner build --delete-conflicting-outputs
      - run: flutter build apk --split-per-abi --no-tree-shake-icons
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*.apk"
          tag: v1.3.1
